name: Code Lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Setup ruff
        run: uv tool install ruff

      # - name: Install dependencies
      #   run: uv sync --all-extras --dev

      - name: Lint
        run: ruff check .

      - name: Format
        run: ruff format --diff .

  code-spell:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Code Spell Check
        uses: streetsidesoftware/cspell-action@v6
        with:
          files: "**"
          config: .cspell.json
          strict: true
          verbose: true
